# Generated by Django 4.0 on 2023-11-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('photo', '0002_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoPost',
            new_name='NewsPost',
        ),
    ]
